"""
Shared System Constants
Fleet Management System
"""

# Vehicle Status Lifecycle Constants (13 States)
VEHICLE_STATUS_DRAFT = "Draft"
VEHICLE_STATUS_AVAILABLE = "Available"
VEHICLE_STATUS_RESERVED = "Reserved"
VEHICLE_STATUS_ASSIGNED = "Assigned"
VEHICLE_STATUS_MAINTENANCE_DUE = "Maintenance Due"
VEHICLE_STATUS_UNDER_MAINTENANCE = "Under Maintenance"
VEHICLE_STATUS_INSPECTION = "Inspection"
VEHICLE_STATUS_OUT_OF_SERVICE = "Out of Service"
VEHICLE_STATUS_INACTIVE = "Inactive"
VEHICLE_STATUS_SOLD = "Sold"
VEHICLE_STATUS_SCRAPPED = "Scrapped"
VEHICLE_STATUS_ARCHIVED = "Archived"

# Legacy alias compatibility
VEHICLE_STATUS_MAINTENANCE = "Under Maintenance"

ALL_VEHICLE_STATUSES = (
	VEHICLE_STATUS_DRAFT,
	VEHICLE_STATUS_AVAILABLE,
	VEHICLE_STATUS_RESERVED,
	VEHICLE_STATUS_ASSIGNED,
	VEHICLE_STATUS_MAINTENANCE_DUE,
	VEHICLE_STATUS_UNDER_MAINTENANCE,
	VEHICLE_STATUS_INSPECTION,
	VEHICLE_STATUS_OUT_OF_SERVICE,
	VEHICLE_STATUS_INACTIVE,
	VEHICLE_STATUS_SOLD,
	VEHICLE_STATUS_SCRAPPED,
	VEHICLE_STATUS_ARCHIVED,
)

# Vehicle Event Types
VEHICLE_EVENT_CREATED = "Vehicle Created"
VEHICLE_EVENT_UPDATED = "Vehicle Updated"
VEHICLE_EVENT_STATUS_CHANGED = "Vehicle Status Changed"
VEHICLE_EVENT_ACTIVATED = "Vehicle Activated"
VEHICLE_EVENT_DEACTIVATED = "Vehicle Deactivated"
VEHICLE_EVENT_ARCHIVED = "Vehicle Archived"
VEHICLE_EVENT_RESTORED = "Vehicle Restored"

ALL_VEHICLE_EVENTS = (
	VEHICLE_EVENT_CREATED,
	VEHICLE_EVENT_UPDATED,
	VEHICLE_EVENT_STATUS_CHANGED,
	VEHICLE_EVENT_ACTIVATED,
	VEHICLE_EVENT_DEACTIVATED,
	VEHICLE_EVENT_ARCHIVED,
	VEHICLE_EVENT_RESTORED,
)

# Assignment Status Constants
ASSIGNMENT_STATUS_DRAFT = "Draft"
ASSIGNMENT_STATUS_ASSIGNED = "Assigned"
ASSIGNMENT_STATUS_ACTIVE = "Active"
ASSIGNMENT_STATUS_COMPLETED = "Completed"
ASSIGNMENT_STATUS_CANCELLED = "Cancelled"

ALL_ASSIGNMENT_STATUSES = (
	ASSIGNMENT_STATUS_DRAFT,
	ASSIGNMENT_STATUS_ASSIGNED,
	ASSIGNMENT_STATUS_ACTIVE,
	ASSIGNMENT_STATUS_COMPLETED,
	ASSIGNMENT_STATUS_CANCELLED,
)

# Maintenance Status Constants
MAINTENANCE_STATUS_SCHEDULED = "Scheduled"
MAINTENANCE_STATUS_IN_PROGRESS = "In Progress"
MAINTENANCE_STATUS_COMPLETED = "Completed"
MAINTENANCE_STATUS_CANCELLED = "Cancelled"
MAINTENANCE_STATUS_OVERDUE = "Overdue"

ALL_MAINTENANCE_STATUSES = (
	MAINTENANCE_STATUS_SCHEDULED,
	MAINTENANCE_STATUS_IN_PROGRESS,
	MAINTENANCE_STATUS_COMPLETED,
	MAINTENANCE_STATUS_CANCELLED,
	MAINTENANCE_STATUS_OVERDUE,
)

# Fuel Entry Status Constants
FUEL_STATUS_DRAFT = "Draft"
FUEL_STATUS_SUBMITTED = "Submitted"
FUEL_STATUS_CANCELLED = "Cancelled"
FUEL_STATUS_VERIFIED = "Verified"

ALL_FUEL_STATUSES = (
	FUEL_STATUS_DRAFT,
	FUEL_STATUS_SUBMITTED,
	FUEL_STATUS_CANCELLED,
	FUEL_STATUS_VERIFIED,
)

# Approval Status Constants
APPROVAL_STATUS_PENDING = "Pending"
APPROVAL_STATUS_APPROVED = "Approved"
APPROVAL_STATUS_REJECTED = "Rejected"
APPROVAL_STATUS_CANCELLED = "Cancelled"

ALL_APPROVAL_STATUSES = (
	APPROVAL_STATUS_PENDING,
	APPROVAL_STATUS_APPROVED,
	APPROVAL_STATUS_REJECTED,
	APPROVAL_STATUS_CANCELLED,
)

# Notification Types
NOTIFICATION_TYPE_MAINTENANCE_DUE = "Maintenance Due"
NOTIFICATION_TYPE_VEHICLE_ASSIGNED = "Vehicle Assigned"
NOTIFICATION_TYPE_VEHICLE_RETURNED = "Vehicle Returned"
NOTIFICATION_TYPE_FUEL_ADDED = "Fuel Added"
NOTIFICATION_TYPE_EXPENSE_CREATED = "Expense Created"
NOTIFICATION_TYPE_INSURANCE_EXPIRY = "Insurance Expiry"
NOTIFICATION_TYPE_REGISTRATION_EXPIRY = "Registration Expiry"

ALL_NOTIFICATION_TYPES = (
	NOTIFICATION_TYPE_MAINTENANCE_DUE,
	NOTIFICATION_TYPE_VEHICLE_ASSIGNED,
	NOTIFICATION_TYPE_VEHICLE_RETURNED,
	NOTIFICATION_TYPE_FUEL_ADDED,
	NOTIFICATION_TYPE_EXPENSE_CREATED,
	NOTIFICATION_TYPE_INSURANCE_EXPIRY,
	NOTIFICATION_TYPE_REGISTRATION_EXPIRY,
)

# Expense Types
EXPENSE_TYPE_FUEL = "Fuel"
EXPENSE_TYPE_MAINTENANCE = "Maintenance"
EXPENSE_TYPE_INSURANCE = "Insurance"
EXPENSE_TYPE_TOLL = "Toll"
EXPENSE_TYPE_PARKING = "Parking"
EXPENSE_TYPE_REPAIR = "Repair"
EXPENSE_TYPE_INSPECTION = "Inspection"
EXPENSE_TYPE_OTHER = "Other"

ALL_EXPENSE_TYPES = (
	EXPENSE_TYPE_FUEL,
	EXPENSE_TYPE_MAINTENANCE,
	EXPENSE_TYPE_INSURANCE,
	EXPENSE_TYPE_TOLL,
	EXPENSE_TYPE_PARKING,
	EXPENSE_TYPE_REPAIR,
	EXPENSE_TYPE_INSPECTION,
	EXPENSE_TYPE_OTHER,
)

# Vehicle Document Types
VEHICLE_DOC_REGISTRATION = "Registration"
VEHICLE_DOC_INSURANCE = "Insurance"
VEHICLE_DOC_FITNESS = "Fitness Certificate"
VEHICLE_DOC_ROAD_TAX = "Road Tax"
VEHICLE_DOC_WARRANTY = "Warranty"
VEHICLE_DOC_PURCHASE_INVOICE = "Purchase Invoice"
VEHICLE_DOC_INSPECTION = "Inspection Report"
VEHICLE_DOC_OTHER = "Other"

ALL_VEHICLE_DOC_TYPES = (
	VEHICLE_DOC_REGISTRATION,
	VEHICLE_DOC_INSURANCE,
	VEHICLE_DOC_FITNESS,
	VEHICLE_DOC_ROAD_TAX,
	VEHICLE_DOC_WARRANTY,
	VEHICLE_DOC_PURCHASE_INVOICE,
	VEHICLE_DOC_INSPECTION,
	VEHICLE_DOC_OTHER,
)

# Distance Units
DISTANCE_UNIT_KM = "KM"
DISTANCE_UNIT_MILES = "Miles"

ALL_DISTANCE_UNITS = (DISTANCE_UNIT_KM, DISTANCE_UNIT_MILES)

# Fuel Units
FUEL_UNIT_LITERS = "Liters"
FUEL_UNIT_GALLONS = "Gallons"

ALL_FUEL_UNITS = (FUEL_UNIT_LITERS, FUEL_UNIT_GALLONS)

# Default Configuration Values
DEFAULT_MAINTENANCE_INTERVAL_KM = 5000
DEFAULT_REMINDER_DISTANCE_KM = 500
DEFAULT_MAX_FUEL_CAPACITY = 500.0
DEFAULT_CURRENCY = "USD"

# Role Names
ROLE_FLEET_MANAGER = "Fleet Manager"
ROLE_FLEET_OFFICER = "Fleet Officer"
ROLE_FLEET_DISPATCHER = "Fleet Dispatcher"
ROLE_FLEET_DRIVER = "Fleet Driver"
ROLE_FLEET_MECHANIC = "Fleet Mechanic"
ROLE_FLEET_AUDITOR = "Fleet Auditor"
ROLE_FLEET_USER = "Fleet User"

ALL_FLEET_ROLES = (
	ROLE_FLEET_MANAGER,
	ROLE_FLEET_OFFICER,
	ROLE_FLEET_DISPATCHER,
	ROLE_FLEET_DRIVER,
	ROLE_FLEET_MECHANIC,
	ROLE_FLEET_AUDITOR,
	ROLE_FLEET_USER,
)

# Cache & Redis Keys
FLEET_SETTINGS_CACHE_KEY = "fleet_management:settings"
