"""
Shared Domain Enums
Fleet Management System
"""

from enum import Enum
from fleet_management import constants


class VehicleStatus(str, Enum):
	DRAFT = constants.VEHICLE_STATUS_DRAFT
	AVAILABLE = constants.VEHICLE_STATUS_AVAILABLE
	RESERVED = constants.VEHICLE_STATUS_RESERVED
	ASSIGNED = constants.VEHICLE_STATUS_ASSIGNED
	MAINTENANCE_DUE = constants.VEHICLE_STATUS_MAINTENANCE_DUE
	UNDER_MAINTENANCE = constants.VEHICLE_STATUS_UNDER_MAINTENANCE
	INSPECTION = constants.VEHICLE_STATUS_INSPECTION
	OUT_OF_SERVICE = constants.VEHICLE_STATUS_OUT_OF_SERVICE
	INACTIVE = constants.VEHICLE_STATUS_INACTIVE
	SOLD = constants.VEHICLE_STATUS_SOLD
	SCRAPPED = constants.VEHICLE_STATUS_SCRAPPED
	ARCHIVED = constants.VEHICLE_STATUS_ARCHIVED
	
	# Legacy alias for backward compatibility
	MAINTENANCE = constants.VEHICLE_STATUS_UNDER_MAINTENANCE


class AssignmentStatus(str, Enum):
	DRAFT = constants.ASSIGNMENT_STATUS_DRAFT
	PENDING_APPROVAL = constants.ASSIGNMENT_STATUS_PENDING_APPROVAL
	APPROVED = constants.ASSIGNMENT_STATUS_APPROVED
	ASSIGNED = constants.ASSIGNMENT_STATUS_ASSIGNED
	IN_USE = constants.ASSIGNMENT_STATUS_IN_USE
	RETURNED = constants.ASSIGNMENT_STATUS_RETURNED
	CLOSED = constants.ASSIGNMENT_STATUS_CLOSED
	CANCELLED = constants.ASSIGNMENT_STATUS_CANCELLED
	
	# Legacy alias
	ACTIVE = constants.ASSIGNMENT_STATUS_ASSIGNED


class AssignmentEventType(str, Enum):
	CREATED = constants.ASSIGNMENT_EVENT_CREATED
	SUBMITTED = constants.ASSIGNMENT_EVENT_SUBMITTED
	APPROVED = constants.ASSIGNMENT_EVENT_APPROVED
	HANDOVER = constants.ASSIGNMENT_EVENT_HANDOVER
	RETURNED = constants.ASSIGNMENT_EVENT_RETURNED
	CLOSED = constants.ASSIGNMENT_EVENT_CLOSED
	CANCELLED = constants.ASSIGNMENT_EVENT_CANCELLED


class VehicleDocumentType(str, Enum):
	REGISTRATION = constants.VEHICLE_DOC_REGISTRATION
	INSURANCE = constants.VEHICLE_DOC_INSURANCE
	FITNESS = constants.VEHICLE_DOC_FITNESS
	ROAD_TAX = constants.VEHICLE_DOC_ROAD_TAX
	WARRANTY = constants.VEHICLE_DOC_WARRANTY
	PURCHASE_INVOICE = constants.VEHICLE_DOC_PURCHASE_INVOICE
	INSPECTION = constants.VEHICLE_DOC_INSPECTION
	OTHER = constants.VEHICLE_DOC_OTHER


class VehicleDocumentStatus(str, Enum):
	DRAFT = "Draft"
	ACTIVE = "Active"
	EXPIRED = "Expired"
	CANCELLED = "Cancelled"
	ARCHIVED = "Archived"


class VehicleImageCategory(str, Enum):
	FRONT = "Front"
	REAR = "Rear"
	LEFT = "Left"
	RIGHT = "Right"
	INTERIOR = "Interior"
	DASHBOARD = "Dashboard"
	ENGINE = "Engine"
	DAMAGE = "Damage"
	OTHER = "Other"


class VehicleEventType(str, Enum):
	CREATED = constants.VEHICLE_EVENT_CREATED
	UPDATED = constants.VEHICLE_EVENT_UPDATED
	STATUS_CHANGED = constants.VEHICLE_EVENT_STATUS_CHANGED
	ACTIVATED = constants.VEHICLE_EVENT_ACTIVATED
	DEACTIVATED = constants.VEHICLE_EVENT_DEACTIVATED
	ARCHIVED = constants.VEHICLE_EVENT_ARCHIVED
	RESTORED = constants.VEHICLE_EVENT_RESTORED


class FuelEntryStatus(str, Enum):
	DRAFT = constants.FUEL_STATUS_DRAFT
	SUBMITTED = constants.FUEL_STATUS_SUBMITTED
	CANCELLED = constants.FUEL_STATUS_CANCELLED
	VERIFIED = constants.FUEL_STATUS_VERIFIED


class FuelEventType(str, Enum):
	CREATED = "Fuel Entry Created"
	SUBMITTED = "Fuel Entry Submitted"
	VERIFIED = "Fuel Entry Verified"
	CANCELLED = "Fuel Entry Cancelled"


class MaintenanceStatus(str, Enum):
	SCHEDULED = constants.MAINTENANCE_STATUS_SCHEDULED
	IN_PROGRESS = constants.MAINTENANCE_STATUS_IN_PROGRESS
	COMPLETED = constants.MAINTENANCE_STATUS_COMPLETED
	CANCELLED = constants.MAINTENANCE_STATUS_CANCELLED
	OVERDUE = constants.MAINTENANCE_STATUS_OVERDUE


class MaintenanceType(str, Enum):
	PREVENTIVE = "Preventive"
	CORRECTIVE = "Corrective"
	EMERGENCY = "Emergency"
	INSPECTION = "Inspection"


class MaintenancePriority(str, Enum):
	LOW = "Low"
	MEDIUM = "Medium"
	HIGH = "High"
	CRITICAL = "Critical"


class MaintenanceEventType(str, Enum):
	CREATED = "Maintenance Created"
	SCHEDULED = "Maintenance Scheduled"
	IN_PROGRESS = "Maintenance In Progress"
	COMPLETED = "Maintenance Completed"
	CANCELLED = "Maintenance Cancelled"


class ApprovalStatus(str, Enum):
	PENDING = constants.APPROVAL_STATUS_PENDING
	APPROVED = constants.APPROVAL_STATUS_APPROVED
	REJECTED = constants.APPROVAL_STATUS_REJECTED
	CANCELLED = constants.APPROVAL_STATUS_CANCELLED


class NotificationType(str, Enum):
	MAINTENANCE_DUE = constants.NOTIFICATION_TYPE_MAINTENANCE_DUE
	VEHICLE_ASSIGNED = constants.NOTIFICATION_TYPE_VEHICLE_ASSIGNED
	VEHICLE_RETURNED = constants.NOTIFICATION_TYPE_VEHICLE_RETURNED
	FUEL_ADDED = constants.NOTIFICATION_TYPE_FUEL_ADDED
	EXPENSE_CREATED = constants.NOTIFICATION_TYPE_EXPENSE_CREATED
	INSURANCE_EXPIRY = constants.NOTIFICATION_TYPE_INSURANCE_EXPIRY
	REGISTRATION_EXPIRY = constants.NOTIFICATION_TYPE_REGISTRATION_EXPIRY


class ExpenseType(str, Enum):
	FUEL = constants.EXPENSE_TYPE_FUEL
	MAINTENANCE = constants.EXPENSE_TYPE_MAINTENANCE
	INSURANCE = constants.EXPENSE_TYPE_INSURANCE
	TOLL = constants.EXPENSE_TYPE_TOLL
	PARKING = constants.EXPENSE_TYPE_PARKING
	REPAIR = constants.EXPENSE_TYPE_REPAIR
	INSPECTION = constants.EXPENSE_TYPE_INSPECTION
	OTHER = constants.EXPENSE_TYPE_OTHER


class DistanceUnit(str, Enum):
	KM = constants.DISTANCE_UNIT_KM
	MILES = constants.DISTANCE_UNIT_MILES


class FuelUnit(str, Enum):
	LITERS = constants.FUEL_UNIT_LITERS
	GALLONS = constants.FUEL_UNIT_GALLONS


class FleetRole(str, Enum):
	MANAGER = constants.ROLE_FLEET_MANAGER
	OFFICER = constants.ROLE_FLEET_OFFICER
	DISPATCHER = constants.ROLE_FLEET_DISPATCHER
	DRIVER = constants.ROLE_FLEET_DRIVER
	MECHANIC = constants.ROLE_FLEET_MECHANIC
	AUDITOR = constants.ROLE_FLEET_AUDITOR
	USER = constants.ROLE_FLEET_USER


class AuditEvent(str, Enum):
	CREATE = "CREATE"
	UPDATE = "UPDATE"
	DELETE = "DELETE"
	ENABLE = "ENABLE"
	DISABLE = "DISABLE"
	IMPORT = "IMPORT"
	EXPORT = "EXPORT"


class TransmissionType(str, Enum):
	MANUAL = "Manual"
	AUTOMATIC = "Automatic"
	SEMI_AUTOMATIC = "Semi-Automatic"
	CVT = "CVT"
	DUAL_CLUTCH = "Dual-Clutch"
