"""
Shared Domain Enums
Fleet Management System
"""

from enum import Enum
from fleet_management import constants


class VehicleStatus(str, Enum):
	ACTIVE = constants.VEHICLE_STATUS_ACTIVE
	IN_SERVICE = constants.VEHICLE_STATUS_IN_SERVICE
	OUT_OF_SERVICE = constants.VEHICLE_STATUS_OUT_OF_SERVICE
	DISPOSED = constants.VEHICLE_STATUS_DISPOSED
	PENDING_INSPECTION = constants.VEHICLE_STATUS_PENDING_INSPECTION


class AssignmentStatus(str, Enum):
	DRAFT = constants.ASSIGNMENT_STATUS_DRAFT
	ASSIGNED = constants.ASSIGNMENT_STATUS_ASSIGNED
	ACTIVE = constants.ASSIGNMENT_STATUS_ACTIVE
	COMPLETED = constants.ASSIGNMENT_STATUS_COMPLETED
	CANCELLED = constants.ASSIGNMENT_STATUS_CANCELLED


class MaintenanceStatus(str, Enum):
	SCHEDULED = constants.MAINTENANCE_STATUS_SCHEDULED
	IN_PROGRESS = constants.MAINTENANCE_STATUS_IN_PROGRESS
	COMPLETED = constants.MAINTENANCE_STATUS_COMPLETED
	CANCELLED = constants.MAINTENANCE_STATUS_CANCELLED
	OVERDUE = constants.MAINTENANCE_STATUS_OVERDUE


class FuelEntryStatus(str, Enum):
	DRAFT = constants.FUEL_STATUS_DRAFT
	SUBMITTED = constants.FUEL_STATUS_SUBMITTED
	CANCELLED = constants.FUEL_STATUS_CANCELLED
	VERIFIED = constants.FUEL_STATUS_VERIFIED


class ApprovalStatus(str, Enum):
	PENDING = constants.APPROVAL_STATUS_PENDING
	APPROVED = constants.APPROVAL_STATUS_APPROVED
	REJECTED = constants.APPROVAL_STATUS_REJECTED
	CANCELLED = constants.APPROVAL_STATUS_CANCELLED


class NotificationType(str, Enum):
	MAINTENANCE_DUE = constants.NOTIFICATION_TYPE_MAINTENANCE_DUE
	VEHICLE_ASSIGNED = constants.NOTIFICATION_TYPE_VEHICLE_ASSIGNED
	VEHICLE_RETURNED = constants.NOTIFICATION_TYPE_VEHICLE_RETURNED
	FUEL_ADDED = constants.NOTIFICATION_TYPE_FUEL_ADDED
	EXPENSE_CREATED = constants.NOTIFICATION_TYPE_EXPENSE_CREATED
	INSURANCE_EXPIRY = constants.NOTIFICATION_TYPE_INSURANCE_EXPIRY
	REGISTRATION_EXPIRY = constants.NOTIFICATION_TYPE_REGISTRATION_EXPIRY


class ExpenseType(str, Enum):
	FUEL = constants.EXPENSE_TYPE_FUEL
	MAINTENANCE = constants.EXPENSE_TYPE_MAINTENANCE
	INSURANCE = constants.EXPENSE_TYPE_INSURANCE
	TOLL = constants.EXPENSE_TYPE_TOLL
	PARKING = constants.EXPENSE_TYPE_PARKING
	REPAIR = constants.EXPENSE_TYPE_REPAIR
	INSPECTION = constants.EXPENSE_TYPE_INSPECTION
	OTHER = constants.EXPENSE_TYPE_OTHER


class DistanceUnit(str, Enum):
	KM = constants.DISTANCE_UNIT_KM
	MILES = constants.DISTANCE_UNIT_MILES


class FuelUnit(str, Enum):
	LITERS = constants.FUEL_UNIT_LITERS
	GALLONS = constants.FUEL_UNIT_GALLONS


class FleetRole(str, Enum):
	MANAGER = constants.ROLE_FLEET_MANAGER
	OFFICER = constants.ROLE_FLEET_OFFICER
	DISPATCHER = constants.ROLE_FLEET_DISPATCHER
	DRIVER = constants.ROLE_FLEET_DRIVER
	MECHANIC = constants.ROLE_FLEET_MECHANIC
	AUDITOR = constants.ROLE_FLEET_AUDITOR
	USER = constants.ROLE_FLEET_USER
